#因为用不着微信 所以就删啦 
#命令相关的 自己看源 或者猜吧 我懒得解释
#支付宝当面付请使用APIv2
alipay:
  #应用ID
  alipay:
  #应用ID
  appId: "2021002115619230"
  #API私钥
  privateKey: "私钥"
  #支付宝API公钥
  publicKey: "公钥"

#充值商品名称 (%price%为付款金额)
itemName: "充值 %price%元"
#充值提示标题栏
title:
  main: "&a&l充值金额 &e&l%price%"
  sub: "&c&l支付完成后商品将自动到账"
  fadeIn: 10
  stay: 120
  fadeOut: 10
#1元=多少游戏货币
#[broadcast] [title] 似乎没用 还会报错 所以 放弃吧 
#尝试使用 [command]代替吧 我的抄作业能力就这样了 
#you can you up 然后踢我一脚 谢谢
type:
  points:
    itemName: "充值 %price%元"
    proportion: 10
    reward:
      - "[command] points give %player% %point%"
      - "[message] &a您已成功氪金 %price% 元"
#      - "[broadcast] &c玩家 %player% 成功氪金 %price% 元"
#      - "[title] &a&l充值成功||&e点券已到账"

  items:
    商品1:
      itemName: "购买商品1"
      price: 1
      reward:
        - "[command] give %player% gold_ingot 5"
        - "[message] &a您已成功购买商品1"
#        - "[broadcast] &c玩家 %player% 充值购买了商品1"

    商品2:
      itemName: "购买商品2"
      price: 2
      reward:
        - "[command] give %player% gold_ingot 10"
        - "[message] &a您已成功购买商品1"
#        - "[broadcast] &c玩家 %player% 充值购买了商品1"
